In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('/content/qoute_dataset.csv')

In [ ]:
df

                                                  quote           Author
0     “The world as we have created it is a process ...  Albert Einstein
1     “It is our choices, Harry, that show what we t...     J.K. Rowling
2     “There are only two ways to live your life. On...  Albert Einstein
3     “The person, be it gentleman or lady, who has ...      Jane Austen
4     “Imperfection is beauty, madness is genius and...   Marilyn Monroe
...                                                 ...              ...
3033      The past beats inside me like a second heart.   John Banville,
3034  Damn, Claire. Warn a guy before you do a face-...    Rachel Caine,
3035  Can you be a girl for a few seconds?""I'm alwa...   Veronica Roth,
3036  That's what fiction is for. It's for getting a...      Tim O'Brien
3037  If we have no peace, it is because we have for...    Mother Teresa

[3038 rows x 2 columns]

In [ ]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes=df['quote']

In [ ]:
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
# We have to pre-process the data

In [ ]:

#Vectorization
#Embedding

In [ ]:
quotes = df['quote'] # Re-initialize quotes to be the Series from df
quotes = quotes.str.lower()

In [ ]:
import string

In [ ]:
translator=str.maketrans(" "," ",string.punctuation)

In [ ]:
quotes=quotes.apply(lambda x:x.translate(translator))

In [ ]:
quotes

0       “the world as we have created it is a process ...
1       “it is our choices harry that show what we tru...
2       “there are only two ways to live your life one...
3       “the person be it gentleman or lady who has no...
4       “imperfection is beauty madness is genius and ...
                              ...
3033         the past beats inside me like a second heart
3034    damn claire warn a guy before you do a facepla...
3035    can you be a girl for a few secondsim always a...
3036    thats what fiction is for its for getting at t...
3037    if we have no peace it is because we have forg...
Name: quote, Length: 3038, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size=10000
tokenizer= Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [ ]:
word_index=tokenizer.word_index
print(len(word_index))

8978

In [ ]:
list(word_index.items())[:10]

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:
sequence=tokenizer.texts_to_sequences(quotes)

In [ ]:
quotes[0]
sequence[0]

[713,
 62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461]

In [ ]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [ ]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [ ]:
x=[]
y=[]

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq=seq[:i]
    output_seq=seq[i]
    x.append(input_seq)
    y.append(output_seq)

In [ ]:
len(x)

85271

In [ ]:
len(y)

85271

In [ ]:
max_len=max(len(x) for x in x)
max_len

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
x_padded = pad_sequences(x, maxlen=max_len, padding='pre')

In [ ]:
x_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [ ]:
x_padded[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 713], dtype=int32)

In [ ]:
y=np.array(y)

In [ ]:
x_padded.shape

(85271, 745)

In [ ]:
y.shape

(85271,)

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
y_categorical = to_categorical(y, num_classes=vocab_size)

In [ ]:
y_categorical.shape

(85271, 10000)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense, SimpleRNN

In [ ]:
embedding_dim=50
rnn_unit=128

In [ ]:
rnn_model=Sequential()

In [ ]:
rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_len))
rnn_model.add(SimpleRNN(units=rnn_unit))
rnn_model.add(Dense(vocab_size,activation='softmax'))

In [ ]:
rnn_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model=Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_unit,return_sequences=False))
lstm_model.add(Dense(vocab_size,activation='softmax'))

In [ ]:
lstm_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epcohs=100
batch_size=128

In [ ]:
# history_rnn=rnn_model.fit(x_padded,y_categorical,epochs=epcohs,
#                           batch_size=batch_size,validation_split=0.1)

In [ ]:
history_lstm=lstm_model.fit(x_padded,y_categorical,epochs=epcohs,
                          batch_size=batch_size,validation_split=0.1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 54ms/step - accuracy: 0.0383 - loss: 6.7605 - val_accuracy: 0.0456 - val_loss: 6.6797
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.0584 - loss: 6.3110 - val_accuracy: 0.0672 - val_loss: 6.5339
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.0822 - loss: 6.0299 - val_accuracy: 0.0847 - val_loss: 6.4525
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.0979 - loss: 5.8150 - val_accuracy: 0.0956 - val_loss: 6.4299
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1089 - loss: 5.6366 - val_accuracy: 0.1005 - val_loss: 6.4174
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1185 - loss: 5.4710 - val_accuracy: 0.1054 - val_loss: 6.4113
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1276 - loss: 5.3111 - val_accuracy: 0.1066 - val_loss: 6.4462
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1362 - loss: 5.1616 - val_accuracy: 0.1085 - val_loss: 6.4813
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1443 - loss: 5.0186 - val_accuracy: 0.1106 - val_loss: 6.5124
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1507 - loss: 4.8831 - val_accuracy: 0.1122 - val_loss: 6.5576
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1586 - loss: 4.7522 - val_accuracy: 0.1116 - val_loss: 6.6187
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1668 - loss: 4.6251 - val_accuracy: 0.1146 - val_loss: 6.6775
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1761 - loss: 4.5006 - val_accuracy: 0.1137 - val_loss: 6.7349
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1848 - loss: 4.3801 - val_accuracy: 0.1167 - val_loss: 6.8011
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1974 - loss: 4.2596 - val_accuracy: 0.1135 - val_loss: 6.8816
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.2100 - loss: 4.1435 - val_accuracy: 0.1132 - val_loss: 6.9547
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2243 - loss: 4.0314 - val_accuracy: 0.1137 - val_loss: 7.0200
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2394 - loss: 3.9248 - val_accuracy: 0.1127 - val_loss: 7.1082
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2538 - loss: 3.8240 - val_accuracy: 0.1161 - val_loss: 7.1723
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.2675 - loss: 3.7286 - val_accuracy: 0.1120 - val_loss: 7.2529
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2806 - loss: 3.6393 - val_accuracy: 0.1117 - val_loss: 7.3312
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2934 - loss: 3.5564 - val_accuracy: 0.1096 - val_loss: 7.4118
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3058 - loss: 3.4776 - val_accuracy: 0.1103 - val_loss: 7.4794
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3170 - loss: 3.4027 - val_accuracy: 0.1103 - val_loss: 7.5524
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3287 - loss: 3.3329 - val_accuracy: 0.1064 - val_loss: 7.6398
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3387 - loss: 3.2653 - val_accuracy: 0.1079 - val_loss: 7.7117
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3507 - loss: 3.1986 - val_accuracy: 0.1062 - val_loss: 7.7721
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3596 - loss: 3.1366 - val_accuracy: 0.1064 - val_loss: 7.8555
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3693 - loss: 3.0776 - val_accuracy: 0.1059 - val_loss: 7.9149
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3799 - loss: 3.0184 - val_accuracy: 0.1041 - val_loss: 7.9872
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3902 - loss: 2.9639 - val_accuracy: 0.1010 - val_loss: 8.0519
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3985 - loss: 2.9092 - val_accuracy: 0.1013 - val_loss: 8.1168
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4076 - loss: 2.8573 - val_accuracy: 0.0985 - val_loss: 8.1772
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.4170 - loss: 2.8061 - val_accuracy: 0.1013 - val_loss: 8.2490
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4252 - loss: 2.7576 - val_accuracy: 0.1005 - val_loss: 8.3014
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4337 - loss: 2.7098 - val_accuracy: 0.0980 - val_loss: 8.3945
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4409 - loss: 2.6649 - val_accuracy: 0.0964 - val_loss: 8.4257
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4498 - loss: 2.6207 - val_accuracy: 0.0962 - val_loss: 8.5056
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4570 - loss: 2.5785 - val_accuracy: 0.0967 - val_loss: 8.5625
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4655 - loss: 2.5348 - val_accuracy: 0.0969 - val_loss: 8.6162
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4736 - loss: 2.4942 - val_accuracy: 0.0949 - val_loss: 8.6839
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4796 - loss: 2.4563 - val_accuracy: 0.0932 - val_loss: 8.7431
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.4876 - loss: 2.4182 - val_accuracy: 0.0960 - val_loss: 8.7929
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4949 - loss: 2.3774 - val_accuracy: 0.0933 - val_loss: 8.8650
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5019 - loss: 2.3428 - val_accuracy: 0.0947 - val_loss: 8.9078
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5074 - loss: 2.3067 - val_accuracy: 0.0929 - val_loss: 8.9856
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5132 - loss: 2.2721 - val_accuracy: 0.0919 - val_loss: 9.0491
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5208 - loss: 2.2389 - val_accuracy: 0.0928 - val_loss: 9.0848
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 55ms/step - accuracy: 0.5272 - loss: 2.2046 - val_accuracy: 0.0922 - val_loss: 9.1399
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5340 - loss: 2.1716 - val_accuracy: 0.0933 - val_loss: 9.2112
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5402 - loss: 2.1410 - val_accuracy: 0.0937 - val_loss: 9.2608
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5455 - loss: 2.1107 - val_accuracy: 0.0912 - val_loss: 9.3092
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5508 - loss: 2.0796 - val_accuracy: 0.0896 - val_loss: 9.3754
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5580 - loss: 2.0511 - val_accuracy: 0.0911 - val_loss: 9.4220
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5632 - loss: 2.0236 - val_accuracy: 0.0876 - val_loss: 9.4879
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5677 - loss: 1.9957 - val_accuracy: 0.0894 - val_loss: 9.5305
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5744 - loss: 1.9664 - val_accuracy: 0.0857 - val_loss: 9.5890
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5791 - loss: 1.9412 - val_accuracy: 0.0905 - val_loss: 9.6502
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5861 - loss: 1.9132 - val_accuracy: 0.0870 - val_loss: 9.7013
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5903 - loss: 1.8890 - val_accuracy: 0.0870 - val_loss: 9.7687
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5963 - loss: 1.8623 - val_accuracy: 0.0858 - val_loss: 9.8176
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6000 - loss: 1.8385 - val_accuracy: 0.0869 - val_loss: 9.8772
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6061 - loss: 1.8155 - val_accuracy: 0.0860 - val_loss: 9.9219
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6108 - loss: 1.7908 - val_accuracy: 0.0847 - val_loss: 9.9698
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6168 - loss: 1.7684 - val_accuracy: 0.0826 - val_loss: 10.0231
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6190 - loss: 1.7466 - val_accuracy: 0.0835 - val_loss: 10.0741
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6251 - loss: 1.7249 - val_accuracy: 0.0813 - val_loss: 10.1381
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6285 - loss: 1.7039 - val_accuracy: 0.0845 - val_loss: 10.1885
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6322 - loss: 1.6826 - val_accuracy: 0.0843 - val_loss: 10.2429
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6378 - loss: 1.6609 - val_accuracy: 0.0814 - val_loss: 10.2798
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6420 - loss: 1.6415 - val_accuracy: 0.0811 - val_loss: 10.3245
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6462 - loss: 1.6218 - val_accuracy: 0.0823 - val_loss: 10.4019
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6501 - loss: 1.6029 - val_accuracy: 0.0809 - val_loss: 10.4477
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6538 - loss: 1.5841 - val_accuracy: 0.0841 - val_loss: 10.5123
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6580 - loss: 1.5643 - val_accuracy: 0.0824 - val_loss: 10.5520
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6615 - loss: 1.5464 - val_accuracy: 0.0809 - val_loss: 10.5898
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6645 - loss: 1.5284 - val_accuracy: 0.0826 - val_loss: 10.6585
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6697 - loss: 1.5107 - val_accuracy: 0.0789 - val_loss: 10.6803
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 55ms/step - accuracy: 0.6723 - loss: 1.4943 - val_accuracy: 0.0792 - val_loss: 10.7483
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6766 - loss: 1.4762 - val_accuracy: 0.0789 - val_loss: 10.8016
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6798 - loss: 1.4609 - val_accuracy: 0.0789 - val_loss: 10.8329
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6839 - loss: 1.4432 - val_accuracy: 0.0796 - val_loss: 10.8896
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6859 - loss: 1.4264 - val_accuracy: 0.0777 - val_loss: 10.9376
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6898 - loss: 1.4122 - val_accuracy: 0.0788 - val_loss: 10.9875
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6945 - loss: 1.3966 - val_accuracy: 0.0787 - val_loss: 11.0324
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6967 - loss: 1.3829 - val_accuracy: 0.0803 - val_loss: 11.1051
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7004 - loss: 1.3671 - val_accuracy: 0.0773 - val_loss: 11.1407
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7038 - loss: 1.3516 - val_accuracy: 0.0776 - val_loss: 11.1732
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7054 - loss: 1.3384 - val_accuracy: 0.0800 - val_loss: 11.2212
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7090 - loss: 1.3235 - val_accuracy: 0.0783 - val_loss: 11.2859
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7128 - loss: 1.3092 - val_accuracy: 0.0787 - val_loss: 11.3330
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7151 - loss: 1.2957 - val_accuracy: 0.0792 - val_loss: 11.3642
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7173 - loss: 1.2837 - val_accuracy: 0.0742 - val_loss: 11.4068
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7216 - loss: 1.2697 - val_accuracy: 0.0788 - val_loss: 11.4658
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7232 - loss: 1.2552 - val_accuracy: 0.0755 - val_loss: 11.5160
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7263 - loss: 1.2437 - val_accuracy: 0.0767 - val_loss: 11.5583
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7283 - loss: 1.2336 - val_accuracy: 0.0782 - val_loss: 11.6108
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7324 - loss: 1.2171 - val_accuracy: 0.0759 - val_loss: 11.6452
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 58ms/step - accuracy: 0.7340 - loss: 1.2067 - val_accuracy: 0.0777 - val_loss: 11.6801
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7376 - loss: 1.1944 - val_accuracy: 0.0775 - val_loss: 11.7410

In [ ]:
# from tensorflow.keras.models import load_model

# lstm_model = load_model("/content/lstm_model (1).h5")
# lstm_model.save("lstm_model.h5")

In [ ]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [ ]:
seed_text = "what are"
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

you

In [ ]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text